### ISSUE TITLE
Empty menu?

### ISSUE THREAD

**Issue by glpzzz** [n3omaster/bachecubano#6]
![image](https://user-images.githubusercontent.com/13596248/73578694-4391fc00-444e-11ea-90f8-b1c30a12c555.png)

**Comment by n3omaster** [comment]
I need a blog writer 🤦‍♂️

**Comment by glpzzz** [comment]
- Hide the link
- go to a page with a we're hiring sign
- read rss from a blog you like and show the links to their posts

On January 31, 2020 6:43:05 PM GMT-05:00, Erich Garcia Cruz <notifications@github.com> wrote:
>I need a blog writer 🤦‍♂️>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/n3omaster/bachecubano/issues/6#issuecomment-580958095

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by n3omaster** [comment]
Done!
